DWAPlannerROS:
  # footprint_model:
  #   type: "polygon" 
  #   vertices: [[-0.24, -0.24], [-0.24, 0.24], [0.24, 0.24], [0.24, -0.24]]
  holonomic_robot: false

  # Robot Configuration Parameters
  max_vel_x: 0.6
  min_vel_x: 0.15
  # max_vel_x_backup: 0.6 
  # min_vel_x_backup: 0.15

  max_vel_y: 0
  min_vel_y: 0

  # The velocity when robot is moving in a straight line
  max_vel_trans: 0.6 
  min_vel_trans: 0.15

  max_vel_theta: 1.0
  min_vel_theta: -1.0
  # max_vel_theta_backup: 1
  # min_vel_theta_backup: -1
  # max_rot_vel: 0.35
  # min_rot_vel: -0.35

  acc_lim_x: 2.0
  acc_lim_y: 0
  acc_lim_theta: 10.0
  # acc_lim_x_backup: 2
  # acc_lim_y_backup: 0
  # acc_lim_theta_backup: 10

  # oscillation_timeout: 10.0
  # oscillation_distance: 0.2

  # Goal Tolerance Parameters
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2
  sim_granularity: 0.025
  vx_samples: 80
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0

  path_distance_bias: 80
  goal_distance_bias: 20.0
  occdist_scale: 0.15
  forward_point_distance: 0.2
  scaling_speed: 0.1
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.05

  publish_traj_pc: true
  publish_cost_grid_pc: true
  
  prune_plane: false
  sim_period: 0.1
  theta_stopped_vel: 0.02
  trans_stopped_vel: 0.02

  # stop_time_buffer: 0.2
  # base_local_planner: "dwa_local_planner/DWAPlannerROS"
  # controller_frequency: 10.0
  # controller_patience: 15.0

  # trajectory_cloud:
  #   cloud_inflation_radius: 0.5
  #   cloud_resolution: 0.1
  #   max_cloud_points: 5000

