global_costmap:
  global_frame: map
  robot_base_frame: base_link

  update_frequency: 5.0
  publish_frequency: 10.0
  # transform_tolerance: 0.5

  # resolution: 0.05
  static_map: true

  # plugins:
  #     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
  #     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
  #     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
  
  # static_layer:
  #   enabled:              true
  #   map_topic:            "/map"
  #   first_map_only:       true

  # inflation_layer:
  #   enabled:              true
  #   # 0.4  0.8
  #   cost_scaling_factor:  10
  #   inflation_radius:     0.8

  # obstacle_layer:
  #   enabled:              true
  #   observation_sources: laser_scan_sensor
  #   footprint_clearing_enabled: true 
  #   laser_scan_sensor: {data_type: LaserScan, sensor_frame: base_link, topic: /scan_filtered, marking: true, clearing: true}
  
